site_name: CSE STARTER GUIDE KIT
site_description: A curated guide and resources kit for CSE students to learn core concepts, tools, and domains.
site_url: https://shadil-rayyan.github.io/cse-student-starter-guide/
repo_url: https://github.com/shadil-rayyan/cse-student-starter-guide
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy

plugins:
  - search
  - minify:
      minify_html: true
  - redirects
  - awesome-pages
  - macros
  - codeinclude

